# Generated by Django 5.2.3 on 2025-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('mairie', 'Mairie'), ('admin', 'Administrateur')], default='user', max_length=20),
        ),
    ]
