# Generated by Django 5.2.3 on 2025-07-04 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'analyse par lot", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_images', models.IntegerField(default=0)),
                ('processed_images', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('results_json', models.JSONField(blank=True, null=True)),
                ('csv_result', models.FileField(blank=True, null=True, upload_to='batch_results/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse par lot',
                'verbose_name_plural': 'Analyses par lot',
                'ordering': ['-created_at'],
            },
        ),
    ]
