# Generated by Django 5.2.3 on 2025-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_batchanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
