# Generated by Django 5.2.3 on 2025-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='quartier_normalized',
            field=models.CharField(blank=True, help_text='Version normalisée du quartier pour les recherches', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='ville_normalized',
            field=models.CharField(blank=True, help_text='Version normalisée de la ville pour les recherches', max_length=100, null=True),
        ),
    ]
