# Generated by Django 5.2.3 on 2025-07-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_quartier_normalized_image_ville_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ville_normalized',
            field=models.CharField(blank=True, help_text='Version normalisée de la ville pour les recherches', max_length=100, null=True),
        ),
    ]
