# Generated by Django 5.2.3 on 2025-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_ville_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classification_dl',
            field=models.CharField(blank=True, choices=[('pleine', 'Pleine'), ('vide', 'Vide')], help_text='Classification Deep Learning avec YOLO', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='confidence_dl',
            field=models.FloatField(blank=True, help_text='Niveau de confiance de la classification DL (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='poubelle',
            name='etat_dl',
            field=models.CharField(blank=True, choices=[('pleine', 'Pleine'), ('vide', 'Vide')], help_text='État déterminé par Deep Learning', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='etat',
            field=models.CharField(choices=[('pleine', 'Pleine'), ('vide', 'Vide')], max_length=20),
        ),
    ]
