# Generated by Django 5.2.3 on 2025-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image_classification_dl_image_confidence_dl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='quartier',
            new_name='rue',
        ),
        migrations.RenameField(
            model_name='poubelle',
            old_name='quartier',
            new_name='rue',
        ),
        migrations.RemoveField(
            model_name='image',
            name='quartier_normalized',
        ),
        migrations.AddField(
            model_name='image',
            name='rue_normalized',
            field=models.CharField(blank=True, help_text='Version normalisée de la rue pour les recherches', max_length=100, null=True),
        ),
    ]
