# Generated by Django 5.2.3 on 2025-07-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_quartier_image_rue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='canny_bottom_count',
            field=models.IntegerField(blank=True, help_text='Nombre de contours détectés dans la partie basse', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='canny_mc',
            field=models.CharField(blank=True, choices=[('pleine', 'Pleine'), ('vide', 'Vide')], help_text='Classification MC (Canny)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='canny_ratio',
            field=models.FloatField(blank=True, help_text='Ratio top/bottom pour la classification MC', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='canny_top_count',
            field=models.IntegerField(blank=True, help_text='Nombre de contours détectés dans la partie haute', null=True),
        ),
    ]
